name: workflows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflows
        run: >-
          docker run --rm
          -v "$GITHUB_WORKSPACE:/repo" -w /repo
          rhysd/actionlint:1.7.7
